import Foundation

/// Offline names for common molecules, keyed by standard InChIKey (computed by RDKit from
/// the structure, so any SMILES spelling of the same molecule finds its name). There is no
/// offline IUPAC name generator for arbitrary structures, so unknown molecules show their
/// formula only. Keys were generated with RDKit from reference SMILES and checked against
/// RDKit's CIP labels for stereo-specific names; `MoleculeNamesTests` re-derives a sample.
enum MoleculeNames {
    struct Name: Equatable, Sendable {
        var common: String
        var iupac: String?
    }

    static func lookup(_ inchiKey: String?) -> Name? {
        inchiKey.flatMap { table[$0] }
    }

    static let table: [String: Name] = [
        "BSYNRYMUTXBXSQ-UHFFFAOYSA-N": Name(common: "Aspirin", iupac: "2-acetyloxybenzoic acid"),
        "RYYVLZVUVIJVGH-UHFFFAOYSA-N": Name(common: "Caffeine", iupac: "1,3,7-trimethylpurine-2,6-dione"),
        "HEFNNWSXXWATRW-UHFFFAOYSA-N": Name(common: "Ibuprofen", iupac: "2-[4-(2-methylpropyl)phenyl]propanoic acid"),
        "WQZGKKKJIJFFOK-VFUOTHLCSA-N": Name(common: "β-D-Glucose", iupac: "(2R,3R,4S,5S,6R)-6-(hydroxymethyl)oxane-2,3,4,5-tetrol"),
        "WQZGKKKJIJFFOK-DVKNGEFBSA-N": Name(common: "α-D-Glucose", iupac: "(2S,3R,4S,5S,6R)-6-(hydroxymethyl)oxane-2,3,4,5-tetrol"),
        "JGSARLDLIJGVTE-MBNYWOFBSA-N": Name(common: "Penicillin G", iupac: "(2S,5R,6R)-3,3-dimethyl-7-oxo-6-[(2-phenylacetyl)amino]-4-thia-1-azabicyclo[3.2.0]heptane-2-carboxylic acid"),
        "LFQSCWFLJHTTHZ-UHFFFAOYSA-N": Name(common: "Ethanol", iupac: "ethanol"),
        "OKKJLVBELUTLKV-UHFFFAOYSA-N": Name(common: "Methanol", iupac: "methanol"),
        "KFZMGEQAYNKOFK-UHFFFAOYSA-N": Name(common: "Isopropanol", iupac: "propan-2-ol"),
        "DKGAVHZHDRPRBM-UHFFFAOYSA-N": Name(common: "tert-Butanol", iupac: "2-methylpropan-2-ol"),
        "ISWSIDIOOBJBQZ-UHFFFAOYSA-N": Name(common: "Phenol", iupac: "phenol"),
        "RTZKZFJDLAIYFH-UHFFFAOYSA-N": Name(common: "Diethyl ether", iupac: "ethoxyethane"),
        "RDOXTESZEPMUJZ-UHFFFAOYSA-N": Name(common: "Anisole", iupac: "methoxybenzene"),
        "IKHGUXGNUITLKF-UHFFFAOYSA-N": Name(common: "Acetaldehyde", iupac: "ethanal"),
        "WSFSSNUMVMOOMR-UHFFFAOYSA-N": Name(common: "Formaldehyde", iupac: "methanal"),
        "CSCPPACGZOOCGX-UHFFFAOYSA-N": Name(common: "Acetone", iupac: "propan-2-one"),
        "JHIVVAPYMSGYDF-UHFFFAOYSA-N": Name(common: "Cyclohexanone", iupac: "cyclohexanone"),
        "QTBSBXVTEAMEQO-UHFFFAOYSA-N": Name(common: "Acetic acid", iupac: "ethanoic acid"),
        "QTBSBXVTEAMEQO-UHFFFAOYSA-M": Name(common: "Acetate", iupac: "ethanoate"),
        "XEKOWRVHYACXOJ-UHFFFAOYSA-N": Name(common: "Ethyl acetate", iupac: "ethyl ethanoate"),
        "DLFVBJFMPXGRIB-UHFFFAOYSA-N": Name(common: "Acetamide", iupac: "ethanamide"),
        "OHLUUHNLEMFGTQ-UHFFFAOYSA-N": Name(common: "N-Methylacetamide", iupac: "N-methylethanamide"),
        "ZMXDDKWLCZADIW-UHFFFAOYSA-N": Name(common: "DMF", iupac: "N,N-dimethylformamide"),
        "XSQUKJJJFZCRTK-UHFFFAOYSA-N": Name(common: "Urea", iupac: "urea"),
        "QUSNBJAOOMFDIB-UHFFFAOYSA-N": Name(common: "Ethylamine", iupac: "ethanamine"),
        "HPNMFZURTQLUMO-UHFFFAOYSA-N": Name(common: "Diethylamine", iupac: "N-ethylethanamine"),
        "ZMANZCXQSJIPKH-UHFFFAOYSA-N": Name(common: "Triethylamine", iupac: "N,N-diethylethanamine"),
        "WEVYAHXRMPXWCK-UHFFFAOYSA-N": Name(common: "Acetonitrile", iupac: "ethanenitrile"),
        "JFDZBHWFFUWGJE-UHFFFAOYSA-N": Name(common: "Benzonitrile", iupac: "benzonitrile"),
        "LQNUZADURLCDLV-UHFFFAOYSA-N": Name(common: "Nitrobenzene", iupac: "nitrobenzene"),
        "SPSSULHKWOKEEL-UHFFFAOYSA-N": Name(common: "TNT", iupac: "2-methyl-1,3,5-trinitrobenzene"),
        "WETWJCDKMRHUPV-UHFFFAOYSA-N": Name(common: "Acetyl chloride", iupac: "ethanoyl chloride"),
        "WFDIJRYMOXRFFG-UHFFFAOYSA-N": Name(common: "Acetic anhydride", iupac: "ethanoic anhydride"),
        "LGRFSURHDFAFJT-UHFFFAOYSA-N": Name(common: "Phthalic anhydride", iupac: "2-benzofuran-1,3-dione"),
        "HRYZWHHZPQKTII-UHFFFAOYSA-N": Name(common: "Chloroethane", iupac: "chloroethane"),
        "HEDRZPFGACZZDS-UHFFFAOYSA-N": Name(common: "Chloroform", iupac: "trichloromethane"),
        "MVPPADPHJFYWMZ-UHFFFAOYSA-N": Name(common: "Chlorobenzene", iupac: "chlorobenzene"),
        "DNJIEGIFACGWOD-UHFFFAOYSA-N": Name(common: "Ethanethiol", iupac: "ethanethiol"),
        "RMVRSNDYEFQCLF-UHFFFAOYSA-N": Name(common: "Thiophenol", iupac: "benzenethiol"),
        "QMMFVYPAHWMCMS-UHFFFAOYSA-N": Name(common: "Dimethyl sulfide", iupac: "methylsulfanylmethane"),
        "FFEARJCKVFRZRR-BYPYZUCNSA-N": Name(common: "L-Methionine", iupac: "(2S)-2-amino-4-methylsulfanylbutanoic acid"),
        "IAYPIBMASNFSPL-UHFFFAOYSA-N": Name(common: "Ethylene oxide", iupac: "oxirane"),
        "UHOVQNZJYSORNB-UHFFFAOYSA-N": Name(common: "Benzene", iupac: "benzene"),
        "JUJWROOIHBZHMG-UHFFFAOYSA-N": Name(common: "Pyridine", iupac: "pyridine"),
        "SIKJAQJRHWYJAI-UHFFFAOYSA-N": Name(common: "Indole", iupac: "1H-indole"),
        "YEJRWHAVMIAJKC-UHFFFAOYSA-N": Name(common: "γ-Butyrolactone", iupac: "oxolan-2-one"),
        "ZYGHJZDHTFUPRJ-UHFFFAOYSA-N": Name(common: "Coumarin", iupac: "chromen-2-one"),
        "JBKVHLHDHHXQEQ-UHFFFAOYSA-N": Name(common: "Caprolactam", iupac: "azepan-2-one"),
        "HEWZVZIVELJPQZ-UHFFFAOYSA-N": Name(common: "2,2-Dimethoxypropane", iupac: "2,2-dimethoxypropane"),
        "VGGSQFUCUMXWEO-UHFFFAOYSA-N": Name(common: "Ethylene", iupac: "ethene"),
        "MWWATHDPGQKSAR-UHFFFAOYSA-N": Name(common: "Propyne", iupac: "prop-1-yne"),
        "HSFWRNGVRCDJHI-UHFFFAOYSA-N": Name(common: "Acetylene", iupac: "ethyne"),
        "RZVAJINKPMORJF-UHFFFAOYSA-N": Name(common: "Paracetamol", iupac: "N-(4-hydroxyphenyl)acetamide"),
        "NNJVILVZKWQKPM-UHFFFAOYSA-N": Name(common: "Lidocaine", iupac: "2-(diethylamino)-N-(2,6-dimethylphenyl)acetamide"),
        "MWOOGOJBHIARFG-UHFFFAOYSA-N": Name(common: "Vanillin", iupac: "4-hydroxy-3-methoxybenzaldehyde"),
        "KJPRLNWUNMBNBZ-QPJJXVBHSA-N": Name(common: "Cinnamaldehyde", iupac: "(E)-3-phenylprop-2-enal"),
        "CZMRCDWAGMRECN-UGDNZRGBSA-N": Name(common: "Sucrose", iupac: nil),
        "MUMGGOZAMZWBJJ-DYKIIFRCSA-N": Name(common: "Testosterone", iupac: nil),
        "HVYWMOMLDIMFJA-DPAQBDIFSA-N": Name(common: "Cholesterol", iupac: nil),
        "BLFLLBZGZJTVJG-UHFFFAOYSA-N": Name(common: "Benzocaine", iupac: "ethyl 4-aminobenzoate"),
        "SNICXCGAKADSCV-JTQLQIEISA-N": Name(common: "Nicotine", iupac: "3-[(2S)-1-methylpyrrolidin-2-yl]pyridine"),
        "VYFYYTLLBUKUHU-UHFFFAOYSA-N": Name(common: "Dopamine", iupac: "4-(2-aminoethyl)benzene-1,2-diol"),
        "JLKIGFTWXXRPMT-UHFFFAOYSA-N": Name(common: "Sulfamethoxazole", iupac: "4-amino-N-(5-methyl-1,2-oxazol-3-yl)benzenesulfonamide"),
        "DHMQDGOQFOQNFH-UHFFFAOYSA-N": Name(common: "Glycine", iupac: "2-aminoacetic acid"),
        "QNAYBMKLOCPYGJ-REOHCLBHSA-N": Name(common: "L-Alanine", iupac: "(2S)-2-aminopropanoic acid"),
        "HUMNYLRZRPPJDN-UHFFFAOYSA-N": Name(common: "Benzaldehyde", iupac: "benzaldehyde"),
        "YGSDEFSMJLZEOE-UHFFFAOYSA-N": Name(common: "Salicylic acid", iupac: "2-hydroxybenzoic acid"),
        "WPYMKLBDIGXBTP-UHFFFAOYSA-N": Name(common: "Benzoic acid", iupac: "benzoic acid"),
        "YXFVVABEGXRONW-UHFFFAOYSA-N": Name(common: "Toluene", iupac: "methylbenzene"),
        "UFWIBTONFRDIAS-UHFFFAOYSA-N": Name(common: "Naphthalene", iupac: "naphthalene"),
        "LYCAIKOWRPUZTN-UHFFFAOYSA-N": Name(common: "Ethylene glycol", iupac: "ethane-1,2-diol"),
        "PEDCQBHIVMGVHV-UHFFFAOYSA-N": Name(common: "Glycerol", iupac: "propane-1,2,3-triol"),
        "JVTAAEKCZFNVCJ-UHFFFAOYSA-N": Name(common: "Lactic acid", iupac: "2-hydroxypropanoic acid"),
        "KRKNYBCHXYNGOX-UHFFFAOYSA-N": Name(common: "Citric acid", iupac: "2-hydroxypropane-1,2,3-tricarboxylic acid"),
        "QZAYGJVTTNCVMB-UHFFFAOYSA-N": Name(common: "Serotonin", iupac: "3-(2-aminoethyl)-1H-indol-5-ol"),
        "AAOVKJBEBIDNHE-UHFFFAOYSA-N": Name(common: "Diazepam", iupac: "7-chloro-1-methyl-5-phenyl-3H-1,4-benzodiazepin-2-one"),
        "VZCYOOQTPOCHFL-OWOJBTEDSA-N": Name(common: "Fumaric acid", iupac: "(E)-but-2-enedioic acid"),
        "VZCYOOQTPOCHFL-UPHRSURJSA-N": Name(common: "Maleic acid", iupac: "(Z)-but-2-enedioic acid"),
        "NLHHRLWOUZZQLW-UHFFFAOYSA-N": Name(common: "Acrylonitrile", iupac: "prop-2-enenitrile"),
        "FUSUHKVFWTUUBE-UHFFFAOYSA-N": Name(common: "Methyl vinyl ketone", iupac: "but-3-en-2-one"),
        "INQOMBQAUSQDDS-UHFFFAOYSA-N": Name(common: "Iodomethane", iupac: "iodomethane"),
        "YKPUWZUDDOIDPM-SOFGYWHQSA-N": Name(common: "Capsaicin", iupac: "(E)-N-[(4-hydroxy-3-methoxyphenyl)methyl]-8-methylnon-6-enamide"),
        "VNWKTOKETHGBQD-UHFFFAOYSA-N": Name(common: "Methane", iupac: "methane"),
        "OTMSDBZUPAUEDD-UHFFFAOYSA-N": Name(common: "Ethane", iupac: "ethane"),
        "ATUOYWHBWRKTHZ-UHFFFAOYSA-N": Name(common: "Propane", iupac: "propane"),
        "IJDNQMDRQITEOD-UHFFFAOYSA-N": Name(common: "Butane", iupac: "butane"),
        "XDTMQSROBMDMFD-UHFFFAOYSA-N": Name(common: "Cyclohexane", iupac: "cyclohexane"),
        "XLYOFNOQVPJJNP-UHFFFAOYSA-N": Name(common: "Water", iupac: "oxidane"),
        "QGZKDVFQNNGYKY-UHFFFAOYSA-N": Name(common: "Ammonia", iupac: "azane"),
        "CURLTUGMZLYLDI-UHFFFAOYSA-N": Name(common: "Carbon dioxide", iupac: "carbon dioxide"),
        "GJRQTCIYDGXPES-UHFFFAOYSA-N": Name(common: "Isobutyl acetate", iupac: "2-methylpropyl acetate"),
        "LRHPLDYGYMQRHN-UHFFFAOYSA-N": Name(common: "1-Butanol", iupac: "butan-1-ol"),
        "BTANRVKWQNVYAZ-BYPYZUCNSA-N": Name(common: "(S)-2-Butanol", iupac: "(2S)-butan-2-ol"),
        "BTANRVKWQNVYAZ-SCSAIBSYSA-N": Name(common: "(R)-2-Butanol", iupac: "(2R)-butan-2-ol"),
        "JVTAAEKCZFNVCJ-REOHCLBHSA-N": Name(common: "L-Lactic acid", iupac: "(2S)-2-hydroxypropanoic acid"),
    ]
}
